import Vue from 'vue';

export const state = () => ({
  animals: {
    floridacow: {
      id: 'floridacow',
      category: 'farmland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    angusbull: {
      id: 'angusbull',
      category: 'farmland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    devonbull: {
      id: 'devonbull',
      category: 'farmland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    hfbull: {
      id: 'hfbull',
      category: 'farmland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    angusox: {
      id: 'angusox',
      category: 'farmland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    devonox: {
      id: 'devonox',
      category: 'farmland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    spotpig: {
      id: 'spotpig',
      category: 'farmland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    berkpig: {
      id: 'berkpig',
      category: 'farmland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    chinapig: {
      id: 'chinapig',
      category: 'farmland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    merinosheep: {
      id: 'merinosheep',
      category: 'farmland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    goat: {
      id: 'goat',
      category: 'farmland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    desertiguana: {
      id: 'desertiguana',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    gilamonster: {
      id: 'gilamonster',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    armadillo: {
      id: 'armadillo',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    bajapronghorn: {
      id: 'bajapronghorn',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    bajapronghornf: {
      id: 'bajapronghornf',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    javelina: {
      id: 'javelina',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    sonoranpronghorn: {
      id: 'sonoranpronghorn',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    sonoranpronghornf: {
      id: 'sonoranpronghornf',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    bighornramd: {
      id: 'bighornramd',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    bighornsheepd: {
      id: 'bighornsheepd',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    bighornram: {
      id: 'bighornram',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    bighornsheep: {
      id: 'bighornsheep',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    blacksnake: {
      id: 'blacksnake',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    cougar: {
      id: 'cougar',
      category: 'desert',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    alligator_sm: {
      id: 'alligator_sm',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    greeniguana: {
      id: 'greeniguana',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    snappingturtle: {
      id: 'snappingturtle',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    panther: {
      id: 'panther',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    flopanther: {
      id: 'flopanther',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    alligator_m: {
      id: 'alligator_m',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    diamondsnake: {
      id: 'diamondsnake',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    midlandsnake: {
      id: 'midlandsnake',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    timbersnake: {
      id: 'timbersnake',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    snakecopperhead_northern: {
      id: 'snakecopperhead_northern',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    snakecopperhead_southern: {
      id: 'snakecopperhead_southern',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    cottonsnake: {
      id: 'cottonsnake',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    northernsnake: {
      id: 'northernsnake',
      category: 'wetland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    rockyelk: {
      id: 'rockyelk',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    rockyelkf: {
      id: 'rockyelkf',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    badger: {
      id: 'badger',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    graywolf: {
      id: 'graywolf',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    timberwolf: {
      id: 'timberwolf',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    bighornramrm: {
      id: 'bighornramrm',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    bighornsheeprm: {
      id: 'bighornsheeprm',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    coyote: {
      id: 'coyote',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    buck: {
      id: 'buck',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    deer: {
      id: 'deer',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    boar: {
      id: 'boar',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    bison: {
      id: 'bison',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    apronghorn: {
      id: 'apronghorn',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    apronghornf: {
      id: 'apronghornf',
      category: 'mountain_and_grassland',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    blackbear: {
      id: 'blackbear',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    beaver: {
      id: 'beaver',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    raccoon: {
      id: 'raccoon',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    redfox: {
      id: 'redfox',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    grayfox: {
      id: 'grayfox',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    silverfox: {
      id: 'silverfox',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    skunk: {
      id: 'skunk',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    opossum: {
      id: 'opossum',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    muskrat: {
      id: 'muskrat',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    westbullmoose: {
      id: 'westbullmoose',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    westernmoose: {
      id: 'westernmoose',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    bear: {
      id: 'bear',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    rabbit: {
      id: 'rabbit',
      category: 'forest_and_river',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    bat: {
      id: 'bat',
      category: 'common_critters',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    bullfog: {
      id: 'bullfog',
      category: 'common_critters',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    chipmunk: {
      id: 'chipmunk',
      category: 'common_critters',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    cubancrab: {
      id: 'cubancrab',
      category: 'common_critters',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    blackrat: {
      id: 'blackrat',
      category: 'common_critters',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    brownrat: {
      id: 'brownrat',
      category: 'common_critters',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    redsquirrel: {
      id: 'redsquirrel',
      category: 'common_critters',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    graysquirrel: {
      id: 'graysquirrel',
      category: 'common_critters',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    blacksquirrel: {
      id: 'blacksquirrel',
      category: 'common_critters',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    toad: {
      id: 'toad',
      category: 'common_critters',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    sdtoad: {
      id: 'sdtoad',
      category: 'common_critters',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_alligator1_net: {
      id: 'legendary_alligator1_net',
      category: 'legendary_dark',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_beaver3_net: {
      id: 'legendary_beaver3_net',
      category: 'legendary_dark',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_bison1_net: {
      id: 'legendary_bison1_net',
      category: 'legendary_dark',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_buck3_net: {
      id: 'legendary_buck3_net',
      category: 'legendary_dark',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_cougar3_net: {
      id: 'legendary_cougar3_net',
      category: 'legendary_dark',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_coyote2_net: {
      id: 'legendary_coyote2_net',
      category: 'legendary_dark',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_elk1_net: {
      id: 'legendary_elk1_net',
      category: 'legendary_dark',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_wolf2_net: {
      id: 'legendary_wolf2_net',
      category: 'legendary_dark',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_panther1_net: {
      id: 'legendary_panther1_net',
      category: 'legendary_dark',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_ram3_net: {
      id: 'legendary_ram3_net',
      category: 'legendary_dark',
      stamped: false,
      samples: 0,
      playstationOnly: true,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_moose2_net: {
      id: 'legendary_moose2_net',
      category: 'legendary_dark',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_beaver2_net: {
      id: 'legendary_beaver2_net',
      category: 'legendary_light',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_bison2_net: {
      id: 'legendary_bison2_net',
      category: 'legendary_light',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_buck2_net: {
      id: 'legendary_buck2_net',
      category: 'legendary_light',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_cougar1_net: {
      id: 'legendary_cougar1_net',
      category: 'legendary_light',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_coyote3_net: {
      id: 'legendary_coyote3_net',
      category: 'legendary_light',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_elk3_net: {
      id: 'legendary_elk3_net',
      category: 'legendary_light',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_wolf3_net: {
      id: 'legendary_wolf3_net',
      category: 'legendary_light',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_panther2_net: {
      id: 'legendary_panther2_net',
      category: 'legendary_light',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_ram1_net: {
      id: 'legendary_ram1_net',
      category: 'legendary_light',
      stamped: false,
      samples: 0,
      playstationOnly: true,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_moose1_net: {
      id: 'legendary_moose1_net',
      category: 'legendary_light',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_alligator2_net: {
      id: 'legendary_alligator2_net',
      category: 'legendary_red_and_blonde',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_alligator3_net: {
      id: 'legendary_alligator3_net',
      category: 'legendary_red_and_blonde',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_bison3_net: {
      id: 'legendary_bison3_net',
      category: 'legendary_red_and_blonde',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_boar2_net: {
      id: 'legendary_boar2_net',
      category: 'legendary_red_and_blonde',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_coyote1_net: {
      id: 'legendary_coyote1_net',
      category: 'legendary_red_and_blonde',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_elk2_net: {
      id: 'legendary_elk2_net',
      category: 'legendary_red_and_blonde',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_wolf1_net: {
      id: 'legendary_wolf1_net',
      category: 'legendary_red_and_blonde',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_bear2_net: {
      id: 'legendary_bear2_net',
      category: 'legendary_red_and_blonde',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_bear3_net: {
      id: 'legendary_bear3_net',
      category: 'legendary_red_and_blonde',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_beaver1_net: {
      id: 'legendary_beaver1_net',
      category: 'legendary_red_and_blonde',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_boar1_net: {
      id: 'legendary_boar1_net',
      category: 'legendary_red_and_blonde',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_moose3_net: {
      id: 'legendary_moose3_net',
      category: 'legendary_red_and_blonde',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_bear1_net: {
      id: 'legendary_bear1_net',
      category: 'legendary_patterned',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_boar3_net: {
      id: 'legendary_boar3_net',
      category: 'legendary_patterned',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_buck1_net: {
      id: 'legendary_buck1_net',
      category: 'legendary_patterned',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_cougar2_net: {
      id: 'legendary_cougar2_net',
      category: 'legendary_patterned',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_fox1_net: {
      id: 'legendary_fox1_net',
      category: 'legendary_patterned',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_fox2_net: {
      id: 'legendary_fox2_net',
      category: 'legendary_patterned',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_fox3_net: {
      id: 'legendary_fox3_net',
      category: 'legendary_patterned',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_panther3_net: {
      id: 'legendary_panther3_net',
      category: 'legendary_patterned',
      stamped: false,
      samples: 0,
      playstationOnly: false,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
    legendary_ram2_net: {
      id: 'legendary_ram2_net',
      category: 'legendary_patterned',
      stamped: false,
      samples: 0,
      playstationOnly: true,
      isLocked: false,
      progress: {
        tracked: false,
        killed: false,
        skinned: false,
        studied: false,
        sedated: false,
        sampled: false,
        photographed: false,
      },
    },
  },
  animalsList: [
    'floridacow',
    'angusbull',
    'devonbull',
    'hfbull',
    'angusox',
    'devonox',
    'spotpig',
    'berkpig',
    'chinapig',
    'merinosheep',
    'goat',
    'desertiguana',
    'gilamonster',
    'armadillo',
    'bajapronghorn',
    'bajapronghornf',
    'javelina',
    'sonoranpronghorn',
    'sonoranpronghornf',
    'bighornramd',
    'bighornsheepd',
    'bighornram',
    'bighornsheep',
    'blacksnake',
    'cougar',
    'alligator_sm',
    'greeniguana',
    'snappingturtle',
    'panther',
    'flopanther',
    'alligator_m',
    'diamondsnake',
    'midlandsnake',
    'timbersnake',
    'snakecopperhead_northern',
    'snakecopperhead_southern',
    'cottonsnake',
    'northernsnake',
    'rockyelk',
    'rockyelkf',
    'badger',
    'graywolf',
    'timberwolf',
    'bighornramrm',
    'bighornsheeprm',
    'coyote',
    'buck',
    'deer',
    'boar',
    'bison',
    'apronghorn',
    'apronghornf',
    'blackbear',
    'beaver',
    'raccoon',
    'redfox',
    'grayfox',
    'silverfox',
    'skunk',
    'opossum',
    'muskrat',
    'westbullmoose',
    'westernmoose',
    'bear',
    'rabbit',
    'bat',
    'bullfog',
    'chipmunk',
    'cubancrab',
    'blackrat',
    'brownrat',
    'redsquirrel',
    'graysquirrel',
    'blacksquirrel',
    'toad',
    'sdtoad',
    'legendary_alligator1_net',
    'legendary_beaver3_net',
    'legendary_bison1_net',
    'legendary_buck3_net',
    'legendary_cougar3_net',
    'legendary_coyote2_net',
    'legendary_elk1_net',
    'legendary_wolf2_net',
    'legendary_panther1_net',
    'legendary_ram3_net',
    'legendary_moose2_net',
    'legendary_beaver2_net',
    'legendary_bison2_net',
    'legendary_buck2_net',
    'legendary_cougar1_net',
    'legendary_coyote3_net',
    'legendary_elk3_net',
    'legendary_wolf3_net',
    'legendary_panther2_net',
    'legendary_ram1_net',
    'legendary_moose1_net',
    'legendary_alligator2_net',
    'legendary_alligator3_net',
    'legendary_bison3_net',
    'legendary_boar2_net',
    'legendary_coyote1_net',
    'legendary_elk2_net',
    'legendary_wolf1_net',
    'legendary_bear2_net',
    'legendary_bear3_net',
    'legendary_beaver1_net',
    'legendary_boar1_net',
    'legendary_moose3_net',
    'legendary_bear1_net',
    'legendary_boar3_net',
    'legendary_buck1_net',
    'legendary_cougar2_net',
    'legendary_fox1_net',
    'legendary_fox2_net',
    'legendary_fox3_net',
    'legendary_panther3_net',
    'legendary_ram2_net',
  ],
});

export const getters = {
  getAnimals: (state, getters, rootState, rootGetters) =>
    state.animalsList
      .map((id) => state.animals[id])
      .filter(
        (animal) =>
          !(animal.playstationOnly && !rootGetters['platform/isPlaystation'])
      ),
  getAnimalsWithCategory: (state, getters) => (category) =>
    getters.getAnimals.filter((animal) => animal.category === category),
};

export const mutations = {
  SET_SAMPLES(state, { id, value }) {
    Vue.set(state.animals[id], 'samples', value);
  },
  SET_STAMPED(state, { id, value }) {
    Vue.set(state.animals[id], 'stamped', value);
  },
};

export const actions = {
  decreaseSamples({ state, commit }, id) {
    const animalSamples = state.animals[id].samples;

    if (animalSamples < 1) return false;

    commit('SET_SAMPLES', { id, value: animalSamples - 1 });
    return true;
  },
  increaseSamples({ state, commit }, id) {
    const animalSamples = state.animals[id].samples;
    commit('SET_SAMPLES', { id, value: animalSamples + 1 });
  },
  stampSample({ commit, dispatch }, id) {
    if (dispatch('decreaseSamples', id))
      commit('SET_STAMPED', { id, value: true });
  },
  revertStamp({ state, commit }, id) {
    const animalSamples = state.animals[id].samples;
    commit('SET_SAMPLES', { id, value: animalSamples + 1 });
    commit('SET_STAMPED', { id, value: false });
  },
};
