export const state = () => ({
  animals: {
    V7OV442ij23pWcAwJLh1n: {
      id: 'V7OV442ij23pWcAwJLh1n',
      name: 'alpine_goat',
      category: '3Amt9rgxHxvUFsWn3Zi6c',
    },
    '2RaYj4XELPlc351w3khsf': {
      id: '2RaYj4XELPlc351w3khsf',
      name: 'angus_bull',
      category: '3Amt9rgxHxvUFsWn3Zi6c',
    },
    _E4OCjx7_OEs9UHRS9n8b: {
      id: '_E4OCjx7_OEs9UHRS9n8b',
      name: 'angus_ox',
      category: '3Amt9rgxHxvUFsWn3Zi6c',
    },
    bAP45sx6oELB3ID19rLfN: {
      id: 'bAP45sx6oELB3ID19rLfN',
      name: 'berkshire_pig',
      category: '3Amt9rgxHxvUFsWn3Zi6c',
    },
    LRgyRS3n0_yTZ4bLaHltt: {
      id: 'LRgyRS3n0_yTZ4bLaHltt',
      name: 'big_china_pig',
      category: '3Amt9rgxHxvUFsWn3Zi6c',
    },
    'ovxknWx6t3BJ2dL_eLoK-': {
      id: 'ovxknWx6t3BJ2dL_eLoK-',
      name: 'devon_bull',
      category: '3Amt9rgxHxvUFsWn3Zi6c',
    },
    '1kUS-8uSxp85hMaseII-O': {
      id: '1kUS-8uSxp85hMaseII-O',
      name: 'devon_ox',
      category: '3Amt9rgxHxvUFsWn3Zi6c',
    },
    _NHJ4uQ24c0oI3fyv3_A9: {
      id: '_NHJ4uQ24c0oI3fyv3_A9',
      name: 'florida_cracker_cow',
      category: '3Amt9rgxHxvUFsWn3Zi6c',
    },
    'hsLXOKVN63Mqf0uJ-l5n5': {
      id: 'hsLXOKVN63Mqf0uJ-l5n5',
      name: 'hereford_bull',
      category: '3Amt9rgxHxvUFsWn3Zi6c',
    },
    'KqEDy5kF-keQWUq_0TVzk': {
      id: 'KqEDy5kF-keQWUq_0TVzk',
      name: 'merino_sheep',
      category: '3Amt9rgxHxvUFsWn3Zi6c',
    },
    _mzlKsrxTuiYeEq8hPV_4: {
      id: '_mzlKsrxTuiYeEq8hPV_4',
      name: 'old_spot_pig',
      category: '3Amt9rgxHxvUFsWn3Zi6c',
    },
    pcE_aQ2Ogtwdc5gDyqT2O: {
      id: 'pcE_aQ2Ogtwdc5gDyqT2O',
      name: 'baja_californian_buck',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    vST9vvMvB1DtIHGqFaRnA: {
      id: 'vST9vvMvB1DtIHGqFaRnA',
      name: 'baja_californian_doe',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    rNvdWQRdV1800Tminkaxx: {
      id: 'rNvdWQRdV1800Tminkaxx',
      name: 'banded_gila_monster',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    '9-vx7nCBCEM-DF-BMeP5R': {
      id: '9-vx7nCBCEM-DF-BMeP5R',
      name: 'black_tailed_rattlesnake',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    yyX0Qqhds2rpXjKkFf8y6: {
      id: 'yyX0Qqhds2rpXjKkFf8y6',
      name: 'collared_peccary',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    'FO-ou80GRBYP0vOBI0tiq': {
      id: 'FO-ou80GRBYP0vOBI0tiq',
      name: 'cougar',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    eL4dfuPo1q7ak1sPUZSgL: {
      id: 'eL4dfuPo1q7ak1sPUZSgL',
      name: 'desert_bighorn_ram',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    '7kvt7uAV9J7WlMP_mXE-n': {
      id: '7kvt7uAV9J7WlMP_mXE-n',
      name: 'desert_bighorn_sheep',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    zlqEB8bfHkgotV1jSQ5wz: {
      id: 'zlqEB8bfHkgotV1jSQ5wz',
      name: 'desert_iguana',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    'pL5BB98HSv9n-ODvTFYA2': {
      id: 'pL5BB98HSv9n-ODvTFYA2',
      name: 'ninebanded_armadillo',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    '7i-Vj8vU1Z90nKsbslq6i': {
      id: '7i-Vj8vU1Z90nKsbslq6i',
      name: 'sierra_nevada_ram',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    '-AFbKoJ8UlJdn0f5vsK7E': {
      id: '-AFbKoJ8UlJdn0f5vsK7E',
      name: 'sierra_nevada_sheep',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    ztEPkaC9GAJ7yeBMFDzNN: {
      id: 'ztEPkaC9GAJ7yeBMFDzNN',
      name: 'sonoran_buck',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    UF_wKCongPMcf3pWeWTLe: {
      id: 'UF_wKCongPMcf3pWeWTLe',
      name: 'sonoran_doe',
      category: 'e_Rd0rQ783aYdN193fkR_',
    },
    RbWjxKDoCtQ1jxe6Y0CSx: {
      id: 'RbWjxKDoCtQ1jxe6Y0CSx',
      name: 'american_alligator_small',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    Il2ccH257dgapiCS6JSj5: {
      id: 'Il2ccH257dgapiCS6JSj5',
      name: 'american_alligator_large',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    'VFTkSQPSSboCLP-1GYNJy': {
      id: 'VFTkSQPSSboCLP-1GYNJy',
      name: 'green_iguana',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    'ilOLEDOr-7u2Zb7u8pvVC': {
      id: 'ilOLEDOr-7u2Zb7u8pvVC',
      name: 'alligator_turtle',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    CzyYnPsCM4EolNILMa5xe: {
      id: 'CzyYnPsCM4EolNILMa5xe',
      name: 'panther',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    'C96yoRAYkmTN4Tz-wcdDb': {
      id: 'C96yoRAYkmTN4Tz-wcdDb',
      name: 'florida_panther',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    '9y9F_HvR0bx_eQt6AsMb2': {
      id: '9y9F_HvR0bx_eQt6AsMb2',
      name: 'diamondback_snake',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    '4iHMnPuxKx2sTlsVnkQwL': {
      id: '4iHMnPuxKx2sTlsVnkQwL',
      name: 'midland_water_snake',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    '8zWeXboTSi5ahdZAHDHWT': {
      id: '8zWeXboTSi5ahdZAHDHWT',
      name: 'timber_snake',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    X_VtzUHdXc5XtYa2lQl2S: {
      id: 'X_VtzUHdXc5XtYa2lQl2S',
      name: 'northern_copperhead_snake',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    '9sDQKGBxtTLT6FZW2whv9': {
      id: '9sDQKGBxtTLT6FZW2whv9',
      name: 'southern_copperhead_snake',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    '5kNp3j49eeaMKRftwBP8I': {
      id: '5kNp3j49eeaMKRftwBP8I',
      name: 'cottonmouth_snake',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    '8WRHXrq7z0m_7lxbs6fkf': {
      id: '8WRHXrq7z0m_7lxbs6fkf',
      name: 'northern_water_snake',
      category: '6h9zXXHQfVBrhsticX1GO',
    },
    'dKU8E9Z-j9iYh8-LYWyiU': {
      id: 'dKU8E9Z-j9iYh8-LYWyiU',
      name: 'american_badger',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    GyouFZliJxUhpTeKlLktc: {
      id: 'GyouFZliJxUhpTeKlLktc',
      name: 'american_bison',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    'Hc8wyuHrJTfw-54t_hcig': {
      id: 'Hc8wyuHrJTfw-54t_hcig',
      name: 'american_buck',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    'mJU-PnZ5Ikf79eck_NZTk': {
      id: 'mJU-PnZ5Ikf79eck_NZTk',
      name: 'american_doe',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    s7b5RLhTzA1mIMtHn_AWO: {
      id: 's7b5RLhTzA1mIMtHn_AWO',
      name: 'california_coyote',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    '5tAs--faKm46PUESNln0m': {
      id: '5tAs--faKm46PUESNln0m',
      name: 'gray_wolf',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    NQLEzFE4WpvTcir2q_es5: {
      id: 'NQLEzFE4WpvTcir2q_es5',
      name: 'rocky_bighorn_ram',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    D1NSQ_IEmiKGjFj4oxcmN: {
      id: 'D1NSQ_IEmiKGjFj4oxcmN',
      name: 'rocky_bighorn_sheep',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    'RlOmNhF9-Tac6-R4OBT0x': {
      id: 'RlOmNhF9-Tac6-R4OBT0x',
      name: 'rocky_bull_elk',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    rUzw_dcmRr8nUo9Qeb8mz: {
      id: 'rUzw_dcmRr8nUo9Qeb8mz',
      name: 'rocky_cow_elk',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    v3BAScsOWeelMukDmFTMU: {
      id: 'v3BAScsOWeelMukDmFTMU',
      name: 'timber_wolf',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    oKspwWj2x6d3JApfg7U8l: {
      id: 'oKspwWj2x6d3JApfg7U8l',
      name: 'whitetail_buck',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    c7xyQOJAE5HxtC0QH7axe: {
      id: 'c7xyQOJAE5HxtC0QH7axe',
      name: 'whitetail_deer',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    '24ekkGkxTa-WS1zsiUkGP': {
      id: '24ekkGkxTa-WS1zsiUkGP',
      name: 'wild_boar',
      category: 'gN64lMrUox3sMdkW7-fVU',
    },
    pucXXGH_hZjB15hKUKQax: {
      id: 'pucXXGH_hZjB15hKUKQax',
      name: 'american_gray_fox',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
    wmeibNxmWLxCT90L3zNPl: {
      id: 'wmeibNxmWLxCT90L3zNPl',
      name: 'american_muskrat',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
    'ZaHDu-fy5030ptGfJ_kqH': {
      id: 'ZaHDu-fy5030ptGfJ_kqH',
      name: 'american_red_fox',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
    IaAYNjkIlGmqDppjkS0EF: {
      id: 'IaAYNjkIlGmqDppjkS0EF',
      name: 'black_bear',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
    hIW2jXglQpCq3vqIdpRiG: {
      id: 'hIW2jXglQpCq3vqIdpRiG',
      name: 'blacktailed_rabbit',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
    ehdVecLEy6RsvWPFvq3ps: {
      id: 'ehdVecLEy6RsvWPFvq3ps',
      name: 'grizzly_bear',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
    '4OD7nI2M6ErBMtX8WjsQx': {
      id: '4OD7nI2M6ErBMtX8WjsQx',
      name: 'north_american_beaver',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
    'Z_2LAjjtm9iSm_bI-EAdZ': {
      id: 'Z_2LAjjtm9iSm_bI-EAdZ',
      name: 'north_american_raccoon',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
    au0R2TdkFSGDpXRS9KVnf: {
      id: 'au0R2TdkFSGDpXRS9KVnf',
      name: 'silver_fox',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
    '5y8kjhfy7Tkwlm0juu11i': {
      id: '5y8kjhfy7Tkwlm0juu11i',
      name: 'striped_skunk',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
    'odcHo_-AhdL_7G95iqrjL': {
      id: 'odcHo_-AhdL_7G95iqrjL',
      name: 'virginia_opossum',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
    WF_q2pJcK2pbvWszPA7XL: {
      id: 'WF_q2pJcK2pbvWszPA7XL',
      name: 'western_bull_moose',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
    bEFutiIeq5jDCvCHjq03G: {
      id: 'bEFutiIeq5jDCvCHjq03G',
      name: 'western_moose',
      category: '11WY3u8Dy-3sw-S9FA0ZX',
    },
  },
  animalsList: [
    'V7OV442ij23pWcAwJLh1n',
    '2RaYj4XELPlc351w3khsf',
    '_E4OCjx7_OEs9UHRS9n8b',
    'bAP45sx6oELB3ID19rLfN',
    'LRgyRS3n0_yTZ4bLaHltt',
    'ovxknWx6t3BJ2dL_eLoK-',
    '1kUS-8uSxp85hMaseII-O',
    '_NHJ4uQ24c0oI3fyv3_A9',
    'hsLXOKVN63Mqf0uJ-l5n5',
    'KqEDy5kF-keQWUq_0TVzk',
    '_mzlKsrxTuiYeEq8hPV_4',
    'pcE_aQ2Ogtwdc5gDyqT2O',
    'vST9vvMvB1DtIHGqFaRnA',
    'rNvdWQRdV1800Tminkaxx',
    '9-vx7nCBCEM-DF-BMeP5R',
    'yyX0Qqhds2rpXjKkFf8y6',
    'FO-ou80GRBYP0vOBI0tiq',
    'eL4dfuPo1q7ak1sPUZSgL',
    '7kvt7uAV9J7WlMP_mXE-n',
    'zlqEB8bfHkgotV1jSQ5wz',
    'pL5BB98HSv9n-ODvTFYA2',
    '7i-Vj8vU1Z90nKsbslq6i',
    '-AFbKoJ8UlJdn0f5vsK7E',
    'ztEPkaC9GAJ7yeBMFDzNN',
    'UF_wKCongPMcf3pWeWTLe',
    'RbWjxKDoCtQ1jxe6Y0CSx',
    'Il2ccH257dgapiCS6JSj5',
    'VFTkSQPSSboCLP-1GYNJy',
    'ilOLEDOr-7u2Zb7u8pvVC',
    'CzyYnPsCM4EolNILMa5xe',
    'C96yoRAYkmTN4Tz-wcdDb',
    '9y9F_HvR0bx_eQt6AsMb2',
    '4iHMnPuxKx2sTlsVnkQwL',
    '8zWeXboTSi5ahdZAHDHWT',
    'X_VtzUHdXc5XtYa2lQl2S',
    '9sDQKGBxtTLT6FZW2whv9',
    '5kNp3j49eeaMKRftwBP8I',
    '8WRHXrq7z0m_7lxbs6fkf',
    'dKU8E9Z-j9iYh8-LYWyiU',
    'GyouFZliJxUhpTeKlLktc',
    'Hc8wyuHrJTfw-54t_hcig',
    'mJU-PnZ5Ikf79eck_NZTk',
    's7b5RLhTzA1mIMtHn_AWO',
    '5tAs--faKm46PUESNln0m',
    'NQLEzFE4WpvTcir2q_es5',
    'D1NSQ_IEmiKGjFj4oxcmN',
    'RlOmNhF9-Tac6-R4OBT0x',
    'rUzw_dcmRr8nUo9Qeb8mz',
    'v3BAScsOWeelMukDmFTMU',
    'oKspwWj2x6d3JApfg7U8l',
    'c7xyQOJAE5HxtC0QH7axe',
    '24ekkGkxTa-WS1zsiUkGP',
    'pucXXGH_hZjB15hKUKQax',
    'wmeibNxmWLxCT90L3zNPl',
    'ZaHDu-fy5030ptGfJ_kqH',
    'IaAYNjkIlGmqDppjkS0EF',
    'hIW2jXglQpCq3vqIdpRiG',
    'ehdVecLEy6RsvWPFvq3ps',
    '4OD7nI2M6ErBMtX8WjsQx',
    'Z_2LAjjtm9iSm_bI-EAdZ',
    'au0R2TdkFSGDpXRS9KVnf',
    '5y8kjhfy7Tkwlm0juu11i',
    'odcHo_-AhdL_7G95iqrjL',
    'WF_q2pJcK2pbvWszPA7XL',
    'bEFutiIeq5jDCvCHjq03G',
  ],
});

export const getters = {
  getAnimals: (state) => state.animalsList.map((id) => state.animals[id]),
  getAnimalsWithCategory: (state, getters) => (category) =>
    getters.getAnimals.filter((animal) => animal.category === category),
};

export const mutations = {};

export const actions = {};
